#!/usr/bin/env python3
"""
Update .gitignore to reflect new directory structure.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).parent

GITIGNORE_ADDITIONS = """
# Output directories (generated by analysis scripts)
outputs/
*.log

# Environment and caches
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
env/
venv/
ENV/
.venv

# IDE and editor files
.vscode/
.idea/
*.swp
*.swo
*~

# Jupyter Notebook
.ipynb_checkpoints/
*.ipynb_checkpoints

# Model files and checkpoints
*.pt
*.pth
*.bin
*.ckpt
checkpoints/
model_output/
model_config/

# Data directories
data/raw/*
data/processed/*
!data/.gitkeep
!data/source_file_mapping.json

# Logs and temporary files
logs/
*.log
*.err
*.out
temp/
tmp/
wandb/

# Configuration with secrets
.env
*.secret
*_secret.*
keys/

# CSV output files (add exceptions for important ones if needed)
*.csv
!config/*.csv

# Batch scripts
batch_scripts/

# Miscellaneous
misc/
missed_files.txt
missing_data.txt
"""

def update_gitignore():
    """Update or create .gitignore file."""
    gitignore_path = REPO_ROOT / '.gitignore'
    
    # Read existing content
    if gitignore_path.exists():
        with open(gitignore_path, 'r') as f:
            existing_content = f.read()
    else:
        existing_content = ""
    
    # Check if we've already added our section
    if "# Output directories (generated by analysis scripts)" in existing_content:
        print("⚠ .gitignore already appears to be updated")
        return False
    
    # Append new content
    with open(gitignore_path, 'a') as f:
        if existing_content and not existing_content.endswith('\n'):
            f.write('\n')
        f.write('\n# === Added by reorganization script ===\n')
        f.write(GITIGNORE_ADDITIONS)
    
    print("✓ Updated .gitignore")
    return True

def create_gitkeep_files():
    """Create .gitkeep files in empty directories that should be tracked."""
    dirs_for_gitkeep = [
        'data',
        'docs',
    ]
    
    for dir_name in dirs_for_gitkeep:
        dir_path = REPO_ROOT / dir_name
        if dir_path.exists():
            gitkeep = dir_path / '.gitkeep'
            if not gitkeep.exists():
                gitkeep.touch()
                print(f"✓ Created {dir_name}/.gitkeep")

def main():
    """Main routine."""
    print("=" * 60)
    print("Updating .gitignore")
    print("=" * 60)
    print()
    
    update_gitignore()
    create_gitkeep_files()
    
    print()
    print("✓ .gitignore update complete")
    print()
    print("Note: Review the .gitignore to ensure it matches your needs.")

if __name__ == '__main__':
    main()
